##Numpy (ndarray) oluşturma

In [1]:
import numpy as np
#ilk olarak burada numpy lib kurma işlemi

In [3]:
a = np.array([1,2,3]) #1D array
b = np.array([[1,2],[3,4]]) #2D array

In [5]:
print(a)
print(b)
print(type(a))
print(a.shape)
print(b.ndim)

[1 2 3]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(3,)
2


##Numpy ile dizi oluşturma fonksiyonları

In [7]:
np.zeros((2,3))
np.ones((3,2))
np.eye(3)
np.arange(0,10,2)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
dizi = np.zeros((3,3))

for i in range(3):
  for j in range(3):
    dizi[i,j]=5

print(dizi)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


##Temel Dizi İşlemleri


In [10]:
print(a)
np.mean(a) #ortalama
np.std(a) #Standart sapma
np.max(a) #maksimum değer
np.min(a) #Minimum değer
np.sum(a) #Toplam

[1 2 3]


np.int64(6)

##Slicing


In [11]:
a = np.array([10,20,30,40,50])

print(a[0])
print(a[1:4])
print(a[::2]) # ikili atlayarak


10
[20 30 40]
[10 30 50]


In [14]:
b = np.array([[1,2,3],[4,5,6]])

print(b[0,1])
print(b[:,1])
print(b[1,:])

2
[2 5]
[4 5 6]


##Mantıksal Filtreleme (Boolean Indexing)

In [16]:
a = np.array([5,10,15,20,25])

mask = a >10 ##[FALSE,FALSE,TRUE,TRUE,TRUE]
filtered = a[mask] #[15,20,25]

a[a<15]=0 #[0,10,15,0,0]

##Boyut Değiştirme

In [17]:
a = np.array([[1,2,3],[4,5,6]])

print(a.shape)
print(a.reshape(3,2))
print(a.reshape(-1,1)) #Otomatik Boyutlandırma: Her satıra 1 eleman

print(a.ravel())  #tek boyutlu vektör (Görünüm kopya değil)
print(a.flatten()) #tek boyutlu vektör (Kopya)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [24]:
a = np.arange(1,13)

print(a.reshape(3,4)) #3x4 formatı
print(a.reshape(4,3)) #4x3 formatı
print(a.reshape(1,a.size)) # tek boyutlu hale getirme
print(a.reshape(a.size,1)) # her satır bir eleman olacak şekilde

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


## Matris İşlemleri

In [28]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B)) # Matris Çarpımı
print(A @ B)  #Bu da matris çarpımının en kısa hali

print(A.T) # A nın transpozu

detA = np.linalg.det(A) #Determinat
print(detA)

tersA = np.linalg.inv(A) # Tersini alma
print(tersA)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


## Rastgele sayılar ve İstatiksel İşlemler

In [29]:
np.random.seed(42)              # Aynı rastgeleliği sağlamak için
np.random.randint(0, 10, 5)     # 0-10 arası 5 tamsayı
np.random.rand(3)               # 0-1 arası 3 sayı
np.random.randn(3, 3)           # Ortalama 0, std 1 olan 3x3 sayı


array([[-0.88523035, -0.41218848, -0.4826188 ],
       [ 0.16416482,  0.23309524,  0.11799461],
       [ 1.46237812,  1.53871497, -2.43910582]])

İstatiksel işlemler

In [30]:
a = np.random.randint(1, 100, 10)

np.mean(a)       # Ortalama
np.median(a)     # Medyan
np.std(a)        # Standart sapma
np.var(a)        # Varyans
np.max(a)        # Maksimum
np.min(a)        # Minimum
np.sort(a)       # Sıralama


array([15, 47, 51, 55, 60, 62, 62, 62, 80, 92])